title: Jacob Portes
url: "https://jacobfulano.github.io"
baseurl: ''
twitter: @JacobianNeuro

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: no # or yes

description: "PhD in Computational Neuroscience"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: '/'
 - name: "Research"
   link: "/research"
 - name: "Teaching"
   link: "/teaching"
 - name: "Notes"
   link: "/notes"
 # - name: "Resume"
 #   link: "resume.pdf"
 - name: "Code"
   link: "/code"
